OOP school library: set up associations
AlaaShaheen2/school-library pull request #3
Opened 2022-11-17 20:26 UTC by AlaaShaheen2

- [ ] Created a class named a classroom.
- [ ] Created the has-many/belongs-to relationship between Classroom and the Student.
- [ ] Created a class as the name of Book.
- [ ] Created a class as the name of Rental.
- [ ] Created the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental.
- [ ] Refactored the files to match the project requirements.
- [ ] Modified README

2022-11-17 21:27 UTC, Munsa1 requested changes
Hi @AlaaShaheen2, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- [ ] Overall you did a great job, just a few issues we need to straighten out and you are good
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 21:27 UTC, Munsa1 commented on rental.rb
> +  def initialize(date, book, _customer)
- [ ] The constructor of Rental should be modified so Person is set in it to break the many-to-many relationship, kindly change `_customer` to `person`.

2022-11-17 21:27 UTC, Munsa1 commented on studen.rb
> +    @classroom = classrniloom
- [ ] It would be nice if you could correct the typo here, as this may affect your project in future milestones by causing an error.

2022-11-17 21:27 UTC, Munsa1 commented on rental.rb
> +  attr_accessor :date, :book, :customer
- [ ] Getters and Setters for @book and @person instance variables should be present, kindly change `customer` to `person`

2022-11-18 13:38 UTC, VICTOR-CHUKWU approved these changes
Hi @AlaaShaheen2 , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 14:11 UTC, merged